CREATE TABLE IF NOT EXISTS Social_Good_Database (
    `Company` VARCHAR(38) CHARACTER SET utf8,
    `Project_Name_for_multiple_projects` VARCHAR(27) CHARACTER SET utf8,
    `Location` VARCHAR(41) CHARACTER SET utf8,
    `Structure` VARCHAR(34) CHARACTER SET utf8,
    `Industry` VARCHAR(40) CHARACTER SET utf8,
    `Website` VARCHAR(149) CHARACTER SET utf8
);
INSERT INTO Social_Good_Database VALUES
    ('4New',NULL,'London, UK','Energy Production Platform','Energy & Environment','https://4new.io/'),
    ('Accenture',NULL,NULL,NULL,NULL,'https://www.accenture.com/us-en/new-applied-now'),
    ('Agora',NULL,NULL,'Voting Platform','Governance','https://agora.vote/'),
    ('Aid:Tech',NULL,NULL,NULL,'Humanitarian/Development Aid','https://aid.technology/'),
    ('AidCoin','AidCoin + AidChain + AidPay','Chasso, Switzerland','Philanthropy/Nonprofit','Humanitarian/Development Aid','https://www.aidcoin.co'),
    ('Airpool',NULL,NULL,'Microcrowdsourcing','Transportation','https://www.airpool.io/'),
    ('Alice',NULL,'London, UK','Crowdfunding','Humanitarian/Development Aid','http://alice.si'),
    ('ALIS Media',NULL,NULL,'News Disaggregation','Media','https://alismedia.jp/'),
    ('Aqua Rights Foundation',NULL,'Nevada','Water Rights Tokenization','Energy & Environment','https://aquarights.com'),
    ('Aragon',NULL,NULL,'Decentralized Organizations','Governance','https://aragon.one/'),
    ('Arcadia Blockchain Technologies',NULL,NULL,'Philanthropy/Nonprofit','Humanitarian/Development Aid','http://www.arcadiablockchain.com/'),
    ('Ascribe',NULL,'Berlin, Germany','Artwork Certification and Database','Arts and Music','https://www.ascribe.io/'),
    ('Asseth',NULL,'France','Philanthropy/Nonprofit','Education','https://www.asseth.fr/en/home/'),
    ('AXEL',NULL,NULL,'Marketplace','Digital Content, Arts & Music','https://axeltoken.com/index'),
    ('BC4G',NULL,'SF/London',NULL,'Think Tank','https://www.blockchainforgood.com/about/'),
    ('Better Chain',NULL,NULL,'Supply Chain Information Reporting','Conflict-Free Resources','https://bcha.in/'),
    ('BitGive',NULL,NULL,NULL,NULL,'https://www.bitgivefoundation.org/'),
    ('BitGive Foundation','GiveTrack','Truckee, CA','Philanthropy/Nonprofit','Humanitarian/Development Aid',' https://www.bitgivefoundation.org/about-us/'),
    ('Blockchain 4 Humanity',NULL,NULL,'Accelerator','Impact Economy','http://www.b4h.world/wellcome-to-blockchain-4-humanity/'),
    ('Blockchain for Change Inc.',NULL,'New York City, NY','Sovereign Identity Service','Governance','https://www.linkedin.com/company/blockchainforchangeinc.'),
    ('Blockchain for Social Impact Coalition',NULL,NULL,'Incubator','Sustainability/Sustainable Cities','https://www.blockchainforsocialimpact.com/about-index/'),
    ('Blockchain Learning Group',NULL,NULL,'Blockchain Education',NULL,'https://blockchainlearninggroup.com/'),
    ('Blockchain4GoodRocks',NULL,NULL,'Meetup Group',NULL,'https://twitter.com/4goodrocks'),
    ('BlockMedx',NULL,NULL,NULL,NULL,'https://blockmedx.com/en/'),
    ('BlueNote',NULL,'Zug, Switzerland','Data Exchange Platform','Energy & Environment, Finance','https://bluenote.world/'),
    ('Chicago Blockchain Project',NULL,'Chicago, IL',NULL,'Sustainability/Sustainable Cities','http://chicagoblockchainproject.com/'),
    ('Ciaspora','Lotus Protocol',NULL,NULL,NULL,'https://ciaspora.com/'),
    ('Ciaspora','Eto',NULL,NULL,NULL,'https://ciaspora.com/'),
    ('Ciaspora','Bondless',NULL,NULL,NULL,'https://ciaspora.com/'),
    ('City of Austin, Texas',NULL,'Austin, TX',NULL,NULL,'https://mayorschallenge.bloomberg.org/ideas/austin/'),
    ('ClimateCoin',NULL,'Zug, Switzerland','Emissions Trading','Energy & Environment','https://climatecoin.io/'),
    ('Coinsailor',NULL,NULL,'Blockchain Education',NULL,'https://coinsailor.glitch.me/'),
    ('Consensys Media','BiFrost',NULL,'Philanthropy/Nonprofit','Humanitarian/Development Aid',NULL),
    ('Decentrl.Agency','Mayfair Blockchain Club','London, UK','Meetup Group',NULL,'https://mayfairbc.squarespace.com/'),
    ('Decred',NULL,'Internet','Consensus Voting Model','Governance','https://decred.org'),
    ('Deloitte','ArtTracktive','Luxembourg','Artwork Certification and Database','Arts and Music','https://www2.deloitte.com/lu/en/pages/technology/articles/blockchain-proof-concept-solve-traceability-issues-art.html'),
    ('Democracy Earth Foundation','Sovereign','Global','Governance Platform','Governance','https://www.democracy.earth/'),
    ('Denominator Group','Blockchain for Vaccines','Geneva, Switzerland','Supply Chain Information Reporting','Healthcare','https://denominatorgroup.org/blockchain'),
    ('Dether',NULL,NULL,'Community/Payment Platform','Finance','https://dether.io/'),
    ('Digital Transformation Agency',NULL,'Australia','Welfare Payment Delivery System','Governance','https://www.zdnet.com/article/welfare-payments-in-australia-could-be-delivered-over-blockchain/'),
    ('Dock',NULL,'Internet','Data Exchange Platform','Technology','https://dock.io'),
    ('DogeCoin',NULL,NULL,NULL,NULL,NULL),
    ('Dubai Government + Dubai 10x',NULL,'Dubai, UAE','Vehicle Database','Transportation','http://dubai10x.ae/dubai-10x-initiative-presents-worlds-1st-vehicle-database/'),
    ('dutyof.care',NULL,NULL,'Compliance Monitoring','Risk Mitigation','https://dutyof.care/'),
    ('EarthCycle',NULL,NULL,NULL,NULL,'http://earthcycle.io/'),
    ('Equity Network',NULL,NULL,'Microcrowdsourcing',NULL,'https://www.equitynetwork.co/#f-a-q'),
    ('Etherisc',NULL,'Zug, Switzerland','Insurance Platform','Healthcare','https://etherisc.com/'),
    ('EthicHub',NULL,'Madrid, Spain','Microlending','Agriculture','https://ethichub.com/'),
    ('Exygy',NULL,'San Francisco, CA','Platform Developer','Sustainability/Sustainable Cities','https://exygy.com'),
    ('FarmaTrust',NULL,NULL,'Supply Chain Platform','Pharmaceuticals, Healthcare','https://www.farmatrust.io/'),
    ('Flyingcarpet',NULL,NULL,NULL,NULL,'https://www.flyingcarpet.network/'),
    ('GiveBytes',NULL,NULL,'Crowdfunding',NULL,'https://givebytes.com/'),
    ('GiveCrypto',NULL,NULL,'Philanthropy/Nonprofit','Humanitarian/Development Aid','https://www.givecrypto.org/'),
    ('Giveth',NULL,NULL,'Donation Platform',NULL,'https://giveth.io/'),
    ('Go Help Fund',NULL,NULL,'Philanthropy/Nonprofit','Humanitarian/Development Aid','https://gohelpfund.com/'),
    ('Green Running','Verv','London, UK',NULL,'Energy & Environment','https://verv.energy/'),
    ('Helperbit',NULL,NULL,'Philanthropy/Nonprofit','Humanitarian/Development Aid','https://app.helperbit.com'),
    ('HIT Foundation',NULL,'Zug, ZG',NULL,NULL,'https://hit.foundation/'),
    ('Ibisa',NULL,NULL,'Microinsurance','Agriculture','https://www.ibisa.network/'),
    ('Inmusik',NULL,NULL,'Community/Payment App','Arts and Music','https://inmusik.co/'),
    ('Inschain',NULL,NULL,'Insurance Platform','Healthcare','https://www.inschain.io'),
    ('Internet of Equals',NULL,NULL,'Protocol','Finance','http://internetofequals.org/'),
    ('IOTA',NULL,'berlin, germany',NULL,NULL,'https://www.iota.org/'),
    ('Iryo Network',NULL,'Republic of Slovenia','Medical Database','Health','https://iryo.io/'),
    ('ixo foundation',NULL,'Zug, Switzerland','Protocol','Impact Evaluation','https://ixo.foundation/'),
    ('ixo foundation',NULL,'Zug, ZG',NULL,NULL,'https://www.linkedin.com/company/ixofoundation/'),
    ('Kora Network',NULL,NULL,NULL,NULL,NULL),
    ('Korea Meeetup',NULL,'Korea',NULL,NULL,'https://www.meetup.com/find/?allMeetups=false&keywords=blockchain&radius=10&userFreeform=Seoul%2C+Korea+(South)&mcId=c1024810&change=yes&sort=default'),
    ('LivingOffset',NULL,NULL,'Emissions Trading','Energy & Environment','https://www.livingoffset.io'),
    ('MineSpider',NULL,NULL,'Supply Chain Information Reporting','Conflict-Free Resources','http://minespider.com/about/'),
    ('Mobilum',NULL,'Gibraltar','Crypto to Fiat Currency Exchange','Finance','https://mobilum.com/'),
    ('Moeda',NULL,'New York City, NY; Brasilia, Brazil','Microlending',NULL,'https://moedaseeds.com/'),
    ('Monegraph',NULL,'Brooklyn, NY','Artwork Certification and Database','Arts and Music','https://monegraph.com/'),
    ('ODEM',NULL,NULL,'Education Platforn','Education','https://odem.io'),
    ('OneRelief',NULL,'Washington, D.C.','Crowdfunding','Humanitarian/Development Aid','http://onereliefapp.com/'),
    ('Origo',NULL,NULL,NULL,NULL,'https://origo.network/#home'),
    ('Ox-Chain',NULL,NULL,NULL,NULL,'http://oxchain.uk/'),
    ('Pale Blue Foundation',NULL,NULL,'Philanthropy/Nonprofit','Humanitarian/Development Aid','https://www.paleblue.foundation/'),
    ('Peace Innovation Institute','The Blockchain Society Lab','The Hague, Netherlands','Research Lab','Peace Promotion','https://www.peaceinnovation.com/blockchain-society-lab/'),
    ('Pixel4Impact',NULL,NULL,'Crowdfunding','Finance','https://pixel4impact.org/'),
    ('Plastic Bank',NULL,'Vancouver, BC','Recycling System','Sustainability/Sustainable Cities','https://www.plasticbank.org/'),
    ('Poseidon',NULL,NULL,NULL,'Energy & Environment','https://poseidon.eco/carbon.html'),
    ('Possible. Social Bank of Human Capital',NULL,NULL,'Microvolunteering','Sustainability/Sustainable Cities','http://www.possible.today/#english'),
    ('PowerLedger',NULL,'Perth, Australia','Energy Trading Platform','Energy & Environment','https://powerledger.io/'),
    ('Right Origins',NULL,NULL,'Supply Chain Platform','Agriculture','https://www.rightorigins.com'),
    ('RIghtMesh',NULL,'Zug, Switzerland','Mobile Mesh Networking Platform','Technology','https://www.rightmesh.io'),
    ('RSK',NULL,'Ciudad Autónoma de Buenos Aire, Argentina','Smart Contracts Platform','Finance','https://www.rsk.co'),
    ('Sacramento Kings','MiningForGood','Sacramento, CA','Philanthropy/Nonprofit',NULL,'https://www.nba.com/kings/archive/MiningForGood'),
    ('SafeNight',NULL,'Dallas, TX','Philanthropy/Nonprofit','Domestic Violence Prevention','http://www.safenightapp.org'),
    ('SANA System',NULL,'Switzerland','Medical Data Storage Platform','Healthcare','http://www.sanasystem.ch/'),
    ('Seedom',NULL,NULL,NULL,NULL,'https://www.seedom.io/'),
    ('Shivom',NULL,NULL,'Genomics Data Platform','Healthcare','https://shivom.io'),
    ('Sikka Token',NULL,NULL,NULL,NULL,NULL),
    ('Skychain',NULL,NULL,'AI Diagnostics Platform','Healthcare','https://skychain.global/'),
    ('Skycoin',NULL,NULL,'Blockchain Application Platform','Data Privacy','https://www.skycoin.net/'),
    ('Slavefreetrade',NULL,NULL,'Supply Chain Information Reporting','Agriculture, Manufacturing','https://www.slavefreetrade.org'),
    ('Social Alpha Foundation',NULL,'Hong Kong','Grant-making Platform',NULL,'https://www.socialalphafoundation.org'),
    ('SolarCoin',NULL,NULL,'Energy Production Platform','Energy & Environment','https://solarcoin.org'),
    ('The Blockchain 2030 Project',NULL,NULL,'Blockchain Education','Sustainability/Sustainable Cities','http://www.startcryptosmartly.com/the-blockchain-2030-project/'),
    ('The British Blockchain Association',NULL,'London, UK','Blockchain Advocacy','Technology, Finance','https://www.britishblockchainassociation.com/'),
    ('The Digital Reserve',NULL,'San Francisco, CA','Microlending & Credit Scoring','Finance','thedigitalreserve.org'),
    ('The Give Foundation',NULL,'Geneva, Geneva','Philanthropy/Nonprofit',NULL,NULL),
    ('Tokenimals',NULL,NULL,'Gamified Platform','Animal Conservation','https://www.tokenimals.com/'),
    ('Tree Credits Foundation',NULL,NULL,'Gamified Platform','Sustainability/Sustainable Cities','http://www.tree-credits.org/'),
    ('Twiga Foods + IBM',NULL,'Kenya','Microlending & Credit Scoring','Finance','https://www.ibm.com/blogs/research/2018/04/ibm-twiga-foods/'),
    ('Tyken',NULL,'Leiden, The Netherlands','Identity Management Database','Humanitarian/Development Aid, Governance','https://tykn.tech'),
    ('Ujo Music',NULL,NULL,NULL,NULL,' https://ujomusic.com/'),
    ('UN World Food Programme',NULL,'Jordan','Philanthropy/Nonprofit','Humanitarian/Development Aid','https://www.technologyreview.com/s/610806/inside-the-jordan-refugee-camp-that-runs-on-blockchain/?platform=hootsuite'),
    ('Unicef','Game Chaingers',NULL,'Philanthropy/Nonprofit','Humanitarian/Development Aid','https://www.chaingers.io/'),
    ('UNICEF Innovation Fund','Blockchain Call',NULL,'Seed Funding','Humanitarian/Development Aid','https://unicefinnovationfund.org/'),
    ('Urban Array',NULL,'Internet','Microcrowdsourcing ',NULL,'https://urbanarray.org/'),
    ('Utopi',NULL,'San Francisco, CA','Philanthropy/Nonprofit','Arts and Music','https://www.utopi.io/'),
    ('Verisart',NULL,NULL,'Artwork Certification and Database','Arts and Music','https://www.verisart.com/'),
    ('Vizsafe',NULL,NULL,'Micocrowdsourcing','Risk Mitigation','https://www.vizsafe.com/'),
    ('WePower',NULL,'Vilnius, Lithuania','Energy Trading Platform','Energy & Environment','https://wepower.network/'),
    ('Women in Blockchain',NULL,'New York City, NY','Meetup Group','Gender Equality','https://www.meetup.com/ko-KR/WomeninBlockchainCommunity/'),
    ('ID2020',NULL,'Manhattan, NY','Identity Management Database','Humanitarian/Development Aid, Governance','https://id2020.org'),
    ('Blockchain Institute & Technology',NULL,'Barcelona, Spain','Thinktank','Education','https://www.bitbcn.org/'),
    ('Skyllz',NULL,'Barcelona, Spain','Skill Validation Protocol','Finance','https://skyllz.org/'),
    ('Exsulcoin',NULL,'Bangladesh (USA, Myanmar)','Education Platform','Education','https://exsulcoin.com/');
